Remove Warnings
nventive/UnoApplicationTemplate pull request #101
Opened 2021-11-03 01:03 UTC by carlh98

GitHub Issue: #

## PR Type

What kind of change does this PR introduce?

- Update packages
- Refactoring (no functional changes, no api changes)

## Description

Remove warning and consolidate nuget packages

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [ ] Interface members are XML documented
- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [ ] [Architecture documents](./doc/Architecture.md) have been updated
- [ ] Tested on all relevant platforms

## Other information

## Internal Issue (If applicable):

2021-11-05 13:20 UTC, baptiste-nv approved these changes

2021-11-05 14:08 UTC, Iguins approved these changes

2021-11-09 14:57 UTC, jeanplevesque requested changes

2021-11-09 14:57 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Tests/ApplicationTemplate.Tests.csproj
> +		<PackageReference Include="Chinook.SectionsNavigation.Reactive" Version="0.4.0-dev.59" />
All Chinook.SectionsNavigation packages should be aligned at the same version

2021-11-09 19:08 UTC, jeanplevesque commented on src/app/ApplicationTemplate.UITests/Constants.cs
> +		public static Platform PlatformUnderTest { get; set; }
Should this be
```
public static Platform PlatformUnderTest { get; } = Platform.Android;
```
?

2021-11-09 20:03 UTC, carlh98 commented on src/app/ApplicationTemplate.UITests/Constants.cs
> +		public static Platform PlatformUnderTest { get; set; }
True I've made the change

2021-11-11 13:30 UTC, jeanplevesque approved these changes

2021-11-11 15:12 UTC, merged