Implement dark mode & basic toggle
nventive/UnoApplicationTemplate pull request #135
Opened 2022-04-21 18:01 UTC by GabrielChouinardLetourneau

GitHub Issue: #

## PR Type

What kind of change does this PR introduce?

- Feature

## Description

Implementation of the Dark mode

- Changes in Brushes and overall cohesion of the themes
- Add basic toggle in settings to change the theme (doesn't save in any way atm/not storing the current theme of the user)

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [ ] Interface members are XML documented
- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [ ] [Architecture documents](./doc/Architecture.md) have been updated
- [ ] Tested on all relevant platforms

## Other information

## Internal Issue (If applicable):

2022-04-21 18:36 UTC, jeanplevesque requested changes

2022-04-21 18:36 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Presentation/Settings/SettingsPageViewModel.cs
> +using Windows.UI.Xaml;
Don't manipulate the view from the presentation layer.

2022-04-21 18:38 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Presentation/Settings/SettingsPageViewModel.cs
> +				.SelectManyDisposePrevious((e, ct) => OnThemeSwitchButtonChange())
Use commands when you want to implement commands.
You should very rarely use `SelectManyDisposePrevious`.

2022-04-21 18:44 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Presentation/Settings/SettingsPageViewModel.cs
> +				.SelectManyDisposePrevious((e, ct) => OnThemeSwitchButtonChange())
FYI you can invoke a command from a ToggleSwitch like this.

```xaml
<ToggleSwitch IsOn="{Binding SomeBoolean, Mode=TwoWay}">
	<interactivity:Interaction.Behaviors>
		<core:EventTriggerBehavior EventName="Toggled">
			<core:InvokeCommandAction Command="{Binding SomeCommand}" />
		</core:EventTriggerBehavior>
	</interactivity:Interaction.Behaviors>
</ToggleSwitch>
```

2022-04-22 16:20 UTC, carlh98 commented on src/app/ApplicationTemplate.UWP/Views/Content/Settings/SettingsPage.xaml
> +	  xmlns:interactivity="using:Microsoft.Xaml.Interactivity"
needed?

2022-04-22 20:20 UTC, carlh98 approved these changes

2022-04-22 21:26 UTC, merged