Review and cleaning of the TextBlock control styles
nventive/UnoApplicationTemplate pull request #156
Opened 2022-05-04 19:34 UTC by GabrielChouinardLetourneau

GitHub Issue: #

## PR Type

What kind of change does this PR introduce?

- Refactoring (no functional changes, no api changes)

## Description

- Usage of MaterialOutlinedTextBoxStyle as default control
- Remove the custom template
- Keep basic style setters

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [ ] Interface members are XML documented
- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [ ] [Architecture documents](./doc/Architecture.md) have been updated
- [ ] Tested on all relevant platforms

## Other information

## Internal Issue (If applicable):

https://nventive.visualstudio.com/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252675

2022-05-04 19:41 UTC, Guidemarcus approved these changes

2022-05-04 19:41 UTC, Guidemarcus commented on src/app/ApplicationTemplate.UWP/Views/Content/Posts/EditPostPage.xaml
> +							 PlaceholderText="Write the joke" />
might want to localize this

2022-05-04 19:41 UTC, Guidemarcus commented on src/app/ApplicationTemplate.UWP/Views/Content/Settings/EditProfilePage.xaml
> +							 android:ImeOptions="Next" />
shouldnt there be a nv:TextBoxBehavior.NextControl="{Binding ElementName=EmailBox}" where nv is nventive.view and ElementName the x:name of the next control you want to focus?

2022-05-05 15:01 UTC, carlh98 requested changes

2022-05-05 15:01 UTC, carlh98 commented on src/app/ApplicationTemplate.Shared/Strings/en/Resources.resw
> -  <data name="CreateAccount_PasswordValidation" xml:space="preserve">
Keep resource

2022-05-05 15:02 UTC, carlh98 approved these changes

2022-05-05 17:24 UTC, merged