Fix StatusBar color
nventive/UnoApplicationTemplate pull request #160
Opened 2022-05-06 16:03 UTC by arianeleonard

GitHub Issue: #

## PR Type

What kind of change does this PR introduce?

- Bugfix

## Description

Fix StatusBar color
Color change depending on the page because of background color changes making the status bar not visible.

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [ ] Interface members are XML documented
- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [ ] [Architecture documents](./doc/Architecture.md) have been updated
- [x] Tested on all relevant platforms

## Other information

## Internal Issue (If applicable):

https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=252413

2022-05-16 18:20 UTC, arianeleonard commented on src/app/ApplicationTemplate.Shared/CoreStartup.cs
> +		private async Task ObserveCurrentViewModel(CancellationToken ct, IServiceProvider services)
I'll add a comment as well to explain this change

2022-05-16 21:15 UTC, carlh98 commented on src/app/ApplicationTemplate.Shared/CoreStartup.cs
> +					if (Window.Current.Content is FrameworkElement root)
I would combine the 2 ifs

2022-05-17 12:12 UTC, jeanplevesque requested changes

2022-05-17 12:12 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/CoreStartup.cs
> +					if (Window.Current.Content is FrameworkElement root)
You should not reference any View from `CoreStartup`. Use `Startup` instead.

2022-05-17 12:12 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/CoreStartup.cs
> +#if __ANDROID__ || __IOS__
Wouldn't it be cleaner if this condition was in the method rather than outside of it?

2022-05-17 18:56 UTC, carlh98 commented on src/app/ApplicationTemplate.Shared.Views/Startup.cs
> +			Type[] vmExceptions =
Maybe vmAlternateColor?

2022-05-17 19:14 UTC, carlh98 commented on src/app/ApplicationTemplate.UWP/Views/Content/Settings/SettingsPage.xaml.cs
> +						Windows.UI.ViewManagement.StatusBar.GetForCurrentView().ForegroundColor = Windows.UI.Colors.Black;
No need for the dispatcher here?

2022-05-18 15:04 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared.Views/Startup.cs
> +		private async Task SetStatusBarColor(CancellationToken ct, IServiceProvider services)
You can probably remove the CancellationToken parameter because it's not used

2022-05-25 21:53 UTC, carlh98 approved these changes

2022-05-26 12:37 UTC, jeanplevesque approved these changes

2022-05-26 14:21 UTC, merged