Fix CreateAccount page UI bugs
nventive/UnoApplicationTemplate pull request #196
Opened 2022-06-29 21:48 UTC by arianeleonard

GitHub Issue: #

## PR Type

What kind of change does this PR introduce?

- Bugfix

## Description

Update checkbox style to handle color change.
Show password validation hints when no password is entered.

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [ ] Interface members are XML documented
- [ ] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [ ] [Architecture documents](./doc/Architecture.md) have been updated
- [x] Tested on all relevant platforms

## Other information

## Internal Issue (If applicable):

https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=255989
https://dev.azure.com/nventive/Practice%20committees/_backlogs/backlog/Mobile%20(.Net)/Features/?workitem=255990

2022-06-30 14:34 UTC, jeanplevesque requested changes

2022-06-30 16:08 UTC, arianeleonard commented on src/app/ApplicationTemplate.Shared/Presentation/Authentication/PasswordFormViewModel.cs
> +			set => this.Set(value);
The observables return null when the password is null or empty. Though, for this specific case, we need them to return false when the password is null or empty.

2022-06-30 18:25 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Presentation/Authentication/PasswordFormViewModel.cs
> +			set => this.Set(value);
You should use private setters here :)

2022-06-30 22:17 UTC, arianeleonard commented on src/app/ApplicationTemplate.Shared/Presentation/Authentication/CreateAccountPageViewModel.cs
> +			else
There is validation in the CreateAccountFormViewModel.

2022-07-05 14:58 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Presentation/Authentication/CreateAccountPageViewModel.cs
> +			else
Right! I just realized that there were 2 separate form VMs.

2022-07-05 14:59 UTC, jeanplevesque approved these changes

2022-07-05 15:01 UTC, merged