build: update refit package version
nventive/UnoApplicationTemplate pull request #419
Opened 2024-12-02 12:42 UTC by mahdichtioui

GitHub Issue: #

## Proposed Changes

 - [ ] Bug fix
 - [ ] Feature
 - [ ] Code style update (formatting)
 - [ ] Refactoring (no functional changes, no api changes)
 - [x] Build or CI related changes
 - [ ] Documentation content changes
 - [ ] Other, please describe:

## Description

Updating the Refit package version from 7.0.0 to 8.0.0

## Impact on version

- [ ] **Major**
  - The template structure was changed.
- [ ] **Minor**
  - New functionalities were added.
- [x] **Patch**
  - A bug in behavior was fixed.
  - Documentation was changed.

## PR Checklist 

### Always applicable
No matter your changes, these checks always apply.
- [ ] Your conventional commits are aligned with the **Impact on version** section.
- [ ] Updated [CHANGELOG.md](../blob/main/CHANGELOG.md).
  - Use the latest Major.Minor.X header if you do a **Patch** change.
  - Create a new Major.Minor.X header if you do a **Minor** or **Major** change.
  - If you create a new header, it aligns with the **Impact on version** section and matches what is generated in the build pipeline.
- [ ] Documentation files were updated according with the changes.
  - Update `README.md` and `TemplateConfig.md` if you made changes to **templating**.
  - Update `AzurePipelines.md` and `APP_README.md` if you made changes to **pipelines**.
  - Update `Diagnostics.md` if you made changes to **diagnostic tools**.
  - Update `Architecture.md` and its diagrams if you made **architecture decisions** or if you introduced new **recipes**.
  - ...and so forth: Make sure you update the documentation files associated to the recipes you changed. Review the topics by looking at the content of the `doc/` folder.
- [ ] Images about the template are referenced from the [wiki](https://github.com/nventive/UnoApplicationTemplate/wiki/Images) and added as images in this git.
- [ ] TODO comments are hints for next steps for users of the template and not planned work.

### Contextual
Based on your changes these checks may not apply.
- [ ] Automated tests for the changes have been added/updated.
- [ ] Tested on all relevant platforms

## Other information

## Internal Issue (If applicable):

2024-12-03 14:01 UTC, lamonfly commented
This should be a major version change as it is a Fix!
Don't forget to go through the PR checklist. It should mention to bump the minor version and update the documentation.

2024-12-04 13:26 UTC, jeanplevesque commented
> This should be a major version change as it is a Fix! Don't forget to go through the PR checklist. It should mention to bump the minor version and update the documentation.

@lamonfly @mahdichtioui  Actually, this repository is not publishing any nuget package that others can install as a dependency. It's an application template so it's closer to an application. In this context, the definition for Major, Minor, and Patch aren't the same (as described in the PR template). In this particular case, you should use a Patch with a `fix:` conventional commit.

2024-12-04 13:31 UTC, jeanplevesque requested changes

2024-12-04 13:31 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Access/ApplicationTemplate.Access.csproj
>  		<PackageReference Include="MallardMessageHandlers" Version="1.2.0" />
You'll also want to update `MallardMessageHandlers` to 2.0.0 (which should be available soon now that your PR merged).

2024-12-04 13:31 UTC, jeanplevesque commented on CHANGELOG.md
> +### Security
You don't need to add subheaders, nor notes. As you can see, we've already done security updates in the past (look at the mention of `System.Text.Json`).

2024-12-05 13:17 UTC, jeanplevesque approved these changes

2024-12-05 13:18 UTC, Soap-141 approved these changes

2024-12-05 13:24 UTC, merged