Prevents concurrency issues when refreshing access tokens
nventive/UnoApplicationTemplate pull request #88
Opened 2021-08-24 14:46 UTC by fperreaultnv

GitHub Issue: #86 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## Description

Using a `ConcurrentAuthenticationTokenProvider<AuthenticationData>` will allow the token to be refreshed only once, even if there are many parallel api calls.

## PR Checklist 
Please check if your PR fulfills the following requirements:

- [x] Interface members are XML documented
- [x] Documentation (XML or comments) has been added and/or existing documentation has been updated
- [x] [Architecture documents](./doc/Architecture.md) have been updated
- [ ] Tested on all relevant platforms

## Other information
Unable to do proper testing at the moment because the Test project does not build (see #87)

## Internal Issue (If applicable):
#86

2021-08-30 13:08 UTC, jeanplevesque commented
> Note: By default the ConcurrentAuthenticationTokenProvider is not implemented in the template.
> Do we have any reasons to believe that we should not make it default?
> theoretically we should always have several calls from a VM trying to refresh their token.

Right, we should change the scaffolding code to leverage the `ConcurrentAuthenticationTokenProvider`.

2021-08-30 21:21 UTC, fperreaultnv commented
> Right, we should change the scaffolding code to leverage the ConcurrentAuthenticationTokenProvider.

I think we first need to make the `ConcurrentAuthenticationTokenProvider` abstract in Mallard, this way, we could derive from it and implement the abstract methods `GetToken`, `NotifySessionExpired` and `RefreshToken` directly in application template. 

Doing this would make the implementation here a lot clearer.

2021-08-30 22:39 UTC, fperreaultnv commented
See https://github.com/nventive/MallardMessageHandlers/pull/61
This would allow injection of IAuthenticationTokenHandler<TAuthenticationToken>

2021-08-31 12:28 UTC, jeanplevesque requested changes

2021-08-31 12:28 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Business/Impl/AuthenticationService.cs
> -	public partial class AuthenticationService : IAuthenticationService, IAuthenticationTokenProvider<AuthenticationData>
You can keep this recipe (`AuthenticationService` implementing `IAuthenticationTokenProvider<AuthenticationData>`) by using composition with `ConcurrentAuthenticationTokenProvider<AuthenticationData>`.

2021-08-31 12:28 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Business/Impl/AuthenticationTokenProvider.cs
> +	public class AuthenticationTokenProvider : IAuthenticationTokenProvider<AuthenticationData>, INotifySessionExpired
You don't need this new class if you keep the previous recipe.

2021-08-31 12:28 UTC, jeanplevesque commented on src/app/ApplicationTemplate.Shared/Business/INotifySessionExpired.cs
> +	public interface INotifySessionExpired
You don't need this new interface if you keep the previous recipe.

2021-08-31 15:02 UTC, jeanplevesque approved these changes

2021-08-31 15:20 UTC, takla21 approved these changes

2021-08-31 15:30 UTC, Iguins approved these changes

2021-09-02 13:23 UTC, fperreaultnv commented
@MatFillion @jeanplevesque I'd like to merge this, but I did not find the time to test it properly, and I'm not really set up to test this on physical devices. I also don't have a mac to test at all on iOS. What can we do?

2021-09-02 13:49 UTC, jeanplevesque commented
@fperreaultnv There are many tests in Mallard for `ConcurrentAuthenticationTokenProvider` and it's being used in real apps. I'm confident we can merge this.

2021-09-02 13:49 UTC, merged